name: Build app
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "inserisci il nome della branch"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup yarn
        run: npm install yarn

      - name: Install dependencies
        run: yarn install
          
      - name: execute build
        run: yarn build
